export const HEADER_LIST_SUCCESS = "HEADER_LIST_SUCCESS"
export const HEADER_LIST_REQUEST = "HEADER_LIST_REQUEST"
export const HEADER_LIST_FAIL = "HEADER_LIST_FAIL"

export const MISSION_LIST_SUCCESS = "MISSION_LIST_SUCCESS"
export const MISSION_LIST_REQUEST = "MISSION_LIST_REQUEST"
export const MISSION_LIST_FAIL = "MISSION_LIST_FAIL"

export const SOLUTION_LIST_SUCCESS = "SOLUTION_LIST_SUCCESS"
export const SOLUTION_LIST_REQUEST= "SOLUTION_LIST_REQUEST"
export const SOLUTION_LIST_FAIL = "SOLUTION_LIST_FAIL"